global:
  service:
    influx: ps-influxdb-service
    postgres: ps-postgres-service
  image:
    pscore: 505891794208.dkr.ecr.ap-northeast-2.amazonaws.com/perfstation/pscore:t3
    influx: influxdb:1.8.3
    postgres: postgres:14.4
    psjmeter: 505891794208.dkr.ecr.ap-northeast-2.amazonaws.com/perfstation/psjmeter:v5.4.2
  replicas:
    psjmeter: 1
  persistentVolumeClaim:
    pscore: ps-core-pv-claim
    influx: ps-influx-pv-claim
    postgres: ps-postgres-pv-claim
  storage:
    influxSize: 10Gi
    postgresSize: 10Gi
  postgres:
    db: ps
    user: admin
    password: admin
  k8sapi:
    url: https://BB9C18D96B046FF57CB140111A33A59A.gr7.us-east-2.eks.amazonaws.com
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InFCR0I3M1NtVE9fT1FqNUlVQlVLV0c3cXpVZTRxRlhRdVRWaFlaZlBFT0UifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InBlcmZzdGF0aW9uIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InBlcmZzdGF0aW9uIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZjIxMjI2MWYtZDJkZi00ODU2LTlhM2QtMGNmNjYxYjM1ZGU5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6cGVyZnN0YXRpb24ifQ.hrmrypR8vQ5aWE2395KWL2ANu4kZIaewSyFzq85ySrl1HGIKJmGnsHsuEUWwJYt8EdsYQGMBJfUitlFYN_shm6Jpwp8SemNGHOkhHhLZIeMgJkdhUFRS5czaeoqnP4W_3pbyRWHMrlu3h4xjXvC-dtX67AY_YoMs7glP0rzwQmJjObfhuajZQVBzjRRDbyBK0AFinN4fC3YIJruQ5tsh2olJo839DUd8DTs9TJBZeRnflJ_Yr433hrNvjLHIy9Vc30Q--Q0SVhfY-f2IssApi1tfNLqf_n0oA8LTY-Cj0rCbfq6S5G6ksQUwcGGWPUmQ5-qN55gUTg5yTfaOEWq65g
