apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ps-jmeter-agent
spec:
  replicas: {{ .Values.global.replicas.psjmeter }}
  serviceName: psjmeter
  selector:
    matchLabels:
      app: ps-jmeter
  template:
    metadata:
      labels:
        app: ps-jmeter
    spec:
      containers:
      - name: ps-jmeter
        image: {{ .Values.global.image.psjmeter }}
        command:
        - /bin/bash
        args: ["-c", "export PATH=/PSJMETER/Java/bin:$PATH;service ssh start;/PSJMETER/bin/jmeter-server;while true; do echo psJmeter; sleep 60;done;"]
        ports:
        - containerPort: 22
        - containerPort: 1099
          protocol: TCP
        - containerPort: 4000
          protocol: TCP
        - containerPort: 4445
          protocol: TCP
        resources:
          requests:
            memory: "3Gi"
            cpu: "2000m"
          limits:
            memory: "3Gi"
            cpu: "2000m"

