apiVersion: v1
kind: Service
metadata:
  name : ps-jmeter-agent
spec:
  type: ClusterIP
  selector:
    app: ps-jmeter
  ports:
  - name : port1
    protocol: TCP
    port: 1099
    targetPort: 1099
  - name : port2
    protocol: TCP
    port: 4000
    targetPort: 4000
  - name : port3
    protocol: TCP
    port: 4445
    targetPort: 4445

